server:
  port: 8081

spring:
  application:
    name: gsc-cloud-user
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        server-addr: 111.230.250.174:8848,111.230.250.174:9848
        namespace: public
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        namespace: ${spring.cloud.nacos.discovery.namespace}
  config:
    import:
      - optional:nacos:datasource.yaml
      - optional:nacos:common.yaml